Circumvent swift release build compiler crash
Only release build fails (debug build is fine)
Only when swift compiler from swiftly is used (xcode swift is fine)

:shrug:

Apparently, swift doesn't like .enumerated() call on my custom ArrSlice for some reason

    $ swift build -c release

    Building for production...
    error: compile command failed due to signal 6 (use -v to see invocation)
    Assertion failed: (hasNoNontrivialLexicalLeaf && "Found non-trivial lexical leaf in non-trivial non-lexical type?!"), function verifyLexicalLowering, file TypeLowering.cpp, line 3218.
    Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
    Stack dump:
    0.      Program arguments: ...
    1.      Apple Swift version 6.2 (swift-6.2-RELEASE)
    2.      Compiling with the current language version
    3.      While evaluating request ASTLoweringRequest(Lowering AST to SIL for module Common)
    4.      While silgen emitFunction SIL function "@$s6Common15parseWorkspaces33_3D3F7A27B2FB7EC543F70E74D5CAF945LL5inputAA13ParsedCliArgsVySayAA15WorkspaceFilterOGGAA17SubArgParserInputV_tF".
     for 'parseWorkspaces(input:)' (at /Users/bobko/a/AeroSpace/Sources/Common/cmdArgs/impl/ListWindowsCmdArgs.swift:102:9)
     #0 0x0000000109ae4f18 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1059dcf18)
     #1 0x0000000109ae3644 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1059db644)
     #2 0x0000000109ae5560 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1059dd560)
     #3 0x00000001968c56a4 (/usr/lib/system/libsystem_platform.dylib+0x1804ad6a4)
     #4 0x000000019688b848 (/usr/lib/system/libsystem_pthread.dylib+0x180473848)
     #5 0x00000001967949e4 (/usr/lib/system/libsystem_c.dylib+0x18037c9e4)
     #6 0x0000000196793c18 (/usr/lib/system/libsystem_c.dylib+0x18037bc18)
     #7 0x0000000109b43654 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x105a3b654)
     #8 0x00000001051c3d60 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1010bbd60)
     #9 0x00000001051c29cc (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1010ba9cc)
    #10 0x00000001051bdbc8 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1010b5bc8)
    #11 0x00000001051bc6b8 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1010b46b8)
    #12 0x00000001051bc520 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1010b4520)
    #13 0x00000001051bc364 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1010b4364)
    #14 0x000000010498fab8 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x100887ab8)
    #15 0x000000010497b460 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x100873460)
    #16 0x000000010497994c (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x10087194c)
    #17 0x000000010497852c (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x10087052c)
    #18 0x00000001049d5f34 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1008cdf34)
    #19 0x00000001049c256c (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1008ba56c)
    #20 0x0000000104a6ed50 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x100966d50)
    #21 0x0000000104a6aaac (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x100962aac)
    #22 0x0000000104a699b8 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1009619b8)
    #23 0x00000001049fe6f0 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1008f66f0)
    #24 0x0000000104966264 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x10085e264)
    #25 0x0000000104967304 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x10085f304)
    #26 0x0000000104964a8c (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x10085ca8c)
    #27 0x0000000104969adc (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x100861adc)
    #28 0x0000000104969ff8 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x100861ff8)
    #29 0x0000000104a69394 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x100961394)
    #30 0x000000010496dfd8 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x100865fd8)
    #31 0x000000010496a364 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x100862364)
    #32 0x000000010439c938 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x100294938)
    #33 0x00000001043a8dc8 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1002a0dc8)
    #34 0x000000010439e3fc (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1002963fc)
    #35 0x000000010439dbb8 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x100295bb8)
    #36 0x00000001041416b4 (/Users/bobko/Library/Developer/Toolchains/swift-6.2-RELEASE.xctoolchain/usr/bin/swift-frontend+0x1000396b4)
    #37 0x00000001964eab98